### ISSUE TITLE
Make the google closure compiler an optional dependency

### ISSUE THREAD

**Issue by agentgt** [vadimv/rsp#3]
The google closure compiler is probably not needed for most dependent projects.

```xml
        <dependency>
            <groupId>com.google.javascript</groupId>
            <artifactId>closure-compiler</artifactId>
            <optional>true</optional>
        </dependency>
```

Ideally you would put the JsCompiler in its own maven module but it looks like this is not a multi-module project.

Just to give you an idea how bloated the closure compiler (it uses basically every google oss project) is I did this to your todo-list app:

```xml
        <dependency>
            <groupId>io.github.vadimv</groupId>
            <artifactId>rsp</artifactId>
            <version>0.2</version>
            <exclusions>
              <exclusion>
                <groupId>com.google.javascript</groupId>
                <artifactId>closure-compiler</artifactId>
              </exclusion>
            </exclusions>
        </dependency>
```

And it went from a 16 MB jar to 4 MB jar with dependencies.

**Comment by vadimv** [comment]
Implemented with `<optional>true</optional>`. Thanks!
